### ISSUE TITLE
[cl] Does not show on ST3 3095

### ISSUE THREAD

**Issue by ptcong** [jprichardson/sublime-js-snippets#18]
When i type `cl` for `console.log`, it does not show. Everything else is ok except this.

**Comment by SgtPooki** [comment]
@ptcong any update on why you closed this? You could help others with your problem's solution.

**Comment by ptcong** [comment]
Just a conflict with jQuery Snippet `closet`, so i customize this to `csl` for myself. 
`cl` still works fine for people if they don't use JQuery Snippet plugin.
